name: Deploy to Server

on:
  push:
    branches: [ main, docker-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Build and Deploy 
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/rc4-telegram-frontend
            git pull origin main
            docker-compose down
            docker-compose up --build -d